version: '3.8'

services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    image: chessrl-train
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    command: ["--iterations", "50", "--self-play-games", "100", "--parallel", "--mcts-simulations", "32"]

  play:
    build:
      context: .
      dockerfile: Dockerfile.gui
    image: chessrl-gui
    volumes:
      - ./models:/app/models
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - PYTHONUNBUFFERED=1
    network_mode: "host"  # Required for X11 forwarding
    depends_on:
      - train
    command: ["--model", "chess_model_final.pt"]