[project]
name = "chessrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "python-chess>=1.999",
    "torch>=2.6.0",
]
